import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { Resvg } from "@resvg/resvg-js";

/**
 * One-off: swap the interim sun mark for the official leaf mark (Brand
 * Guidelines v1.0) across the standalone social + marketing SVGs that aren't
 * regenerated by gen-social.ts, then re-render their covers/PNGs.
 */
const root = process.cwd();
const GREEN = "#7BAA94";
const AMBER = "#F5B52E";
const NAVY = "#232A32";
const CREAM = "#ECE6D6";
const DARK = "#3C5A4C";

function leafPath(x: number, y: number, s: number): string {
  const r = s / 2;
  return (
    `M ${x} ${y} L ${x + r} ${y} A ${r} ${r} 0 0 1 ${x + s} ${y + r} ` +
    `L ${x + s} ${y + s} L ${x + r} ${y + s} A ${r} ${r} 0 0 1 ${x} ${y + r} Z`
  );
}

/** Leaf mark centred at (cx,cy), sized to the old sun footprint of radius r. */
function leafMark(cx: number, cy: number, r: number, nColor: string): string {
  const k = r * 0.0384;
  const tx = cx - 50 * k;
  const ty = cy - 50 * k;
  const inner =
    `<path d="${leafPath(16, 16, 68)}" fill="none" stroke="${GREEN}" stroke-width="8" stroke-linejoin="round" stroke-linecap="round"/>` +
    `<text x="45" y="64" font-family="Inter, Arial, sans-serif" font-size="44" font-weight="700" fill="${nColor}" text-anchor="middle">n</text>` +
    `<circle cx="64" cy="59" r="5.5" fill="${AMBER}"/>`;
  return `<g transform="translate(${tx.toFixed(1)},${ty.toFixed(1)}) scale(${k.toFixed(3)})">${inner}</g>`;
}

// Matches the sun mark: amber-ray <g> + green disc + white "n".
const SUN =
  /<g stroke="#F5B52E"[^>]*>(?:<line[^>]*\/>)+<\/g><circle cx="([\d.]+)" cy="([\d.]+)" r="([\d.]+)" fill="#7BAA94"\/><text[^>]*>n<\/text>/g;

function patch(file: string, nColor: string): boolean {
  const p = join(root, file);
  let s = readFileSync(p, "utf8");
  let hit = false;
  s = s.replace(SUN, (_m, cx, cy, r) => {
    hit = true;
    return leafMark(+cx, +cy, +r, nColor);
  });
  if (hit) writeFileSync(p, s);
  console.log(hit ? "  patched" : "  (no sun mark)", file);
  return hit;
}

// Light-background assets → navy "n".
[
  "public/social/day01-school-letter.svg",
  "public/social/day01-cover.svg",
  "public/social/demo-school-email.svg",
  "public/social/demo-school-email-cover.svg",
  "assets/marketing/feature.svg",
  "assets/marketing/promo.svg",
].forEach((f) => patch(f, NAVY));

// Dark tile avatar → cream "n".
patch("public/social/tiktok-avatar.svg", CREAM);

function render(svgFile: string, pngFile: string, width: number) {
  const svg = readFileSync(join(root, svgFile), "utf8");
  writeFileSync(join(root, pngFile), new Resvg(svg, { fitTo: { mode: "width", value: width } }).render().asPng());
  console.log("  rendered", pngFile);
}

render("public/social/day01-cover.svg", "public/social/day01-cover.png", 1080);
render("public/social/demo-school-email-cover.svg", "public/social/demo-school-email-cover.png", 1080);
render("public/social/tiktok-avatar.svg", "public/social/tiktok-avatar.png", 720);
render("assets/marketing/feature.svg", "public/marketing/feature-graphic.png", 1024);
render("assets/marketing/promo.svg", "public/marketing/promo.png", 1200);

void DARK;
